//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptxOnline.Web.PasswordRecoveryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/DSS.Service.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CryptxOnline.Web.PasswordRecoveryService.NewPasswordSettingFromRecoveryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryBeginResponse))]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CryptxOnline.Web.PasswordRecoveryService.ServiceError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CryptxOnline.Web.PasswordRecoveryService.ServiceResponse.ServiceStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CryptxOnline.Web.PasswordRecoveryService.ServiceError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CryptxOnline.Web.PasswordRecoveryService.ServiceResponse.ServiceStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse.ServiceStatus", Namespace="http://schemas.datacontract.org/2004/07/DSS.Service.Response")]
        public enum ServiceStatus : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Success = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Failed = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceError", Namespace="http://schemas.datacontract.org/2004/07/DSS.Service.Error")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryError))]
    public partial class ServiceError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordRecoveryResponse", Namespace="http://schemas.datacontract.org/2004/07/DSS.Service.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CryptxOnline.Web.PasswordRecoveryService.NewPasswordSettingFromRecoveryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryBeginResponse))]
    public partial class PasswordRecoveryResponse : CryptxOnline.Web.PasswordRecoveryService.ServiceResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse.RecoveryState> StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse.RecoveryState> State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PasswordRecoveryResponse.RecoveryState", Namespace="http://schemas.datacontract.org/2004/07/DSS.Service.Response")]
        public enum RecoveryState : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UserExist = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Reject = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Active = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PhoneConfirmationWait = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            WrongPhone = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SmsConfirmationWait = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SmsConfirmationUsed = 50,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SmsSendingError = 51,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SmsConfirmationWasUsed = 52,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            WrongSmsConfirmation = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RecoveryEmailSent = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RecoveryEmailUsed = 70,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RecoveryEmailSendingError = 71,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RecoveryEmailWasUsed = 72,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ban = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Expire = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KobilWait = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KobilAccept = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KobilOff = 12,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KobilReject = 13,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            KobilDeviceWait = 14,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewPasswordSettingFromRecoveryResponse", Namespace="http://schemas.datacontract.org/2004/07/DSS.Service.Response")]
    [System.SerializableAttribute()]
    public partial class NewPasswordSettingFromRecoveryResponse : CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> RecoveryTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> RecoveryToken {
            get {
                return this.RecoveryTokenField;
            }
            set {
                if ((this.RecoveryTokenField.Equals(value) != true)) {
                    this.RecoveryTokenField = value;
                    this.RaisePropertyChanged("RecoveryToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordRecoveryBeginResponse", Namespace="http://schemas.datacontract.org/2004/07/DSS.Service.Response")]
    [System.SerializableAttribute()]
    public partial class PasswordRecoveryBeginResponse : CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> RecoveryTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> RecoveryToken {
            get {
                return this.RecoveryTokenField;
            }
            set {
                if ((this.RecoveryTokenField.Equals(value) != true)) {
                    this.RecoveryTokenField = value;
                    this.RaisePropertyChanged("RecoveryToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordRecoveryError", Namespace="http://schemas.datacontract.org/2004/07/DSS.Service.Error")]
    [System.SerializableAttribute()]
    public partial class PasswordRecoveryError : CryptxOnline.Web.PasswordRecoveryService.ServiceError {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PasswordRecoveryService.IPasswordRecoveryService")]
    public interface IPasswordRecoveryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordRecoveryService/BeginPasswordRecovery", ReplyAction="http://tempuri.org/IPasswordRecoveryService/BeginPasswordRecoveryResponse")]
        CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryBeginResponse BeginPasswordRecovery(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordRecoveryService/CheckRecoveryPhone", ReplyAction="http://tempuri.org/IPasswordRecoveryService/CheckRecoveryPhoneResponse")]
        CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse CheckRecoveryPhone(string phone, System.Guid recoveryTokenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordRecoveryService/EmailRecoveryConfirmation", ReplyAction="http://tempuri.org/IPasswordRecoveryService/EmailRecoveryConfirmationResponse")]
        CryptxOnline.Web.PasswordRecoveryService.NewPasswordSettingFromRecoveryResponse EmailRecoveryConfirmation(string emailConfirmationData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordRecoveryService/SmsRecoveryConfirmation", ReplyAction="http://tempuri.org/IPasswordRecoveryService/SmsRecoveryConfirmationResponse")]
        CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse SmsRecoveryConfirmation(string smsConfirmationData, System.Guid recoveryTokenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordRecoveryService/ResendSmsRecoveryConfirmation", ReplyAction="http://tempuri.org/IPasswordRecoveryService/ResendSmsRecoveryConfirmationResponse" +
            "")]
        CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse ResendSmsRecoveryConfirmation(System.Guid recoveryTokenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordRecoveryService/KobilRecoveryConfirmation", ReplyAction="http://tempuri.org/IPasswordRecoveryService/KobilRecoveryConfirmationResponse")]
        CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse KobilRecoveryConfirmation(System.Guid recoveryTokenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordRecoveryService/NewPasswordFromEmailRecoverySet", ReplyAction="http://tempuri.org/IPasswordRecoveryService/NewPasswordFromEmailRecoverySetRespon" +
            "se")]
        CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse NewPasswordFromEmailRecoverySet(string pwd, System.Guid recoveryTokenId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPasswordRecoveryServiceChannel : CryptxOnline.Web.PasswordRecoveryService.IPasswordRecoveryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PasswordRecoveryServiceClient : System.ServiceModel.ClientBase<CryptxOnline.Web.PasswordRecoveryService.IPasswordRecoveryService>, CryptxOnline.Web.PasswordRecoveryService.IPasswordRecoveryService {
        
        public PasswordRecoveryServiceClient() {
        }
        
        public PasswordRecoveryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PasswordRecoveryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordRecoveryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordRecoveryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryBeginResponse BeginPasswordRecovery(string phone) {
            return base.Channel.BeginPasswordRecovery(phone);
        }
        
        public CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse CheckRecoveryPhone(string phone, System.Guid recoveryTokenId) {
            return base.Channel.CheckRecoveryPhone(phone, recoveryTokenId);
        }
        
        public CryptxOnline.Web.PasswordRecoveryService.NewPasswordSettingFromRecoveryResponse EmailRecoveryConfirmation(string emailConfirmationData) {
            return base.Channel.EmailRecoveryConfirmation(emailConfirmationData);
        }
        
        public CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse SmsRecoveryConfirmation(string smsConfirmationData, System.Guid recoveryTokenId) {
            return base.Channel.SmsRecoveryConfirmation(smsConfirmationData, recoveryTokenId);
        }
        
        public CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse ResendSmsRecoveryConfirmation(System.Guid recoveryTokenId) {
            return base.Channel.ResendSmsRecoveryConfirmation(recoveryTokenId);
        }
        
        public CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse KobilRecoveryConfirmation(System.Guid recoveryTokenId) {
            return base.Channel.KobilRecoveryConfirmation(recoveryTokenId);
        }
        
        public CryptxOnline.Web.PasswordRecoveryService.PasswordRecoveryResponse NewPasswordFromEmailRecoverySet(string pwd, System.Guid recoveryTokenId) {
            return base.Channel.NewPasswordFromEmailRecoverySet(pwd, recoveryTokenId);
        }
    }
}
